#!/bin/sh

# A script to automatically copy the ticket number from a branch
# into the footer of the commit message.

commit_message_file=$1
commit_source=$2
commit_message_template=$(git config --get commit.template)
commit_message_template_contents=$(cat "$commit_message_template")

add_to_commit_message_body() {
  echo "$1" >> "$commit_message_file"
}

if [ "$commit_source" = "template" ]
then
  echo "" > "$commit_message_file"

  add_to_commit_message_body "$commit_message_template_contents"

  branch_name=$(git rev-parse --abbrev-ref HEAD)
  ticket_number=$(echo "$branch_name" | cut -f1,2 -d'-' | tr '[:lower:]' '[:upper:]' | grep -E '^[A-Za-z]+-[0-9]+$')

  # If our ticket number is valid and matches our regex, then include it in
  # our commit footer.
  #
  # For now, we consider a ticket to be valid if we have any number of letters
  # followed by a single hyphen, followed by an number of integers.
  ticket_number_validated=$(echo "$ticket_number" | grep -E '^[A-Za-z]+-[0-9]+$')

  if [ "$ticket_number_validated" != "" ]
  then
    add_to_commit_message_body "${ticket_number}"
  fi
fi
